dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
sudo: false
install:
  - "pip install -q flake8 pylint pytest six"
before_script:
  - "flake8 tests src setup.py"
  - "pylint -E src/richenum"
  - "pylint -E setup.py"
script: "python setup.py test"
